Fix: コンパイルエラー
頭が溶けてて直っているかどうかわかんない。再帰関数の型を間違うと
全体が型エラーになって困る……

app\Main.hs:8:14: error:
    ? Couldn't match type ▒eInt -> String▒f with ▒e[Char]▒f
      Expected type: String
        Actual type: Int -> String
    ? Probable cause: ▒efizz_buzz_string_t▒f is applied to too few arguments
      In the second argument of ▒e($)▒f, namely ▒efizz_buzz_string_t s▒f
      In a stmt of a 'do' block: putStrLn $ fizz_buzz_string_t s
      In the expression:
        do s <- return 1000000000 :: IO Int
           putStrLn $ fizz_buzz_string_t s
  |
8 |   putStrLn $ fizz_buzz_string_t s
  |              ^^^^^^^^^^^^^^^^^^^^

app\Main.hs:52:3: error:
    ? Couldn't match expected type ▒e(Int, Int)▒f
                  with actual type ▒eInt -> ((Int, Int), Int)▒f
    ? The equation(s) for ▒ego▒f have two arguments,
      but its type ▒e(Int, Int) -> (Int, Int)▒f has only one
      In an equation for ▒efizz_buzz_class▒f:
          fizz_buzz_class n
            = go (n, 1)
            where
                go :: (Int, Int) -> (Int, Int)
                go n k = let ... in if n <= c then ... else go ...
   |
52 |   go n k = let c = fizz_buzz_class_size k in
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

app\Main.hs:53:12: error:
    ? Couldn't match expected type ▒e(Int, Int)▒f with actual type ▒eInt▒f
    ? In the second argument of ▒e(<=)▒f, namely ▒ec▒f
      In the expression: n <= c
      In the expression: if n <= c then (n, k) else go (n - c, k + 1)
   |
53 |    if n <= c then (n, k) else go (n - c, k + 1)
   |            ^

app\Main.hs:53:31: error:
    ? Couldn't match type ▒eInt▒f with ▒e(Int, Int)▒f
      Expected type: ((Int, Int), Int)
        Actual type: (Int, Int)
    ? In the expression: go (n - c, k + 1)
      In the expression: if n <= c then (n, k) else go (n - c, k + 1)
      In the expression:
        let c = fizz_buzz_class_size k
        in if n <= c then (n, k) else go (n - c, k + 1)
   |
53 |    if n <= c then (n, k) else go (n - c, k + 1)
   |                               ^^^^^^^^^^^^^^^^^

app\Main.hs:53:35: error:
    ? Couldn't match expected type ▒eInt▒f with actual type ▒e(Int, Int)▒f
    ? In the expression: n - c
      In the first argument of ▒ego▒f, namely ▒e(n - c, k + 1)▒f
      In the expression: go (n - c, k + 1)
   |
53 |    if n <= c then (n, k) else go (n - c, k + 1)
   |                                   ^^^^^

app\Main.hs:53:39: error:
    ? Couldn't match expected type ▒e(Int, Int)▒f with actual type ▒eInt▒f
    ? In the second argument of ▒e(-)▒f, namely ▒ec▒f
      In the expression: n - c
      In the first argument of ▒ego▒f, namely ▒e(n - c, k + 1)▒f
   |
53 |    if n <= c then (n, k) else go (n - c, k + 1)
   |